name: MineCord
main: com.lith.minecord.Plugin

version: 0.0.4
api-version: 1.20

description: A MineCraft x Discord integration plugin
author: Lith
website: https://github.com/ImLith/MC-MineCord

depend: [LithCore]
softdepend: []

commands:
  dcReload:
    description: Reload minecord configs
    usage: /<command>
    permission: minecord.reload

permissions:
  minecord.reload:
    description: Use the /dcReload command
    default: op
